name: tennis_friends_demo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.5+1.0.5

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.6
  provider: ^6.0.2
  numeric_keyboard: ^1.1.0
  google_maps_flutter: ^2.1.1
  flutter_speed_dial: ^5.0.0+1
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  flutter_naver_map: ^0.10.3
  geolocator: ^8.2.0
  http: ^0.13.4
  change_app_package_name: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: SairaCondensed
      fonts:
        - asset: fonts/SairaCondensed-Bold.ttf
          weight: 800
        - asset: fonts/SairaCondensed-Regular.ttf
        - asset: fonts/SairaCondensed-Medium.ttf
          weight: 500

